# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f00145e657a97a9cef8a6679ca3dd1fbd4d8bd897595ec289eb2514afe57f28896fb3319b0ff31bc04506c6663fed1f683db84f0d20e32dfb7e1e872a704380d

test:
  secret_key_base: 1b0fc0d2262aeb2fb6324909437cdaa7dc62d2dcbc13d6a1e3ac239a04e42fe5c31d288a427a12eec7ebdb1a11fb9d94a9c99991c832afbd2560f5aea8485377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
